FROM rust:1.90-bookworm

RUN apt-get update && apt-get install -y \
    libgdal-dev \
    libclang-dev \
    clang \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install bacon

WORKDIR /app

COPY Cargo.lock Cargo.toml bacon.toml /app/
COPY ./src/ /app/src/
COPY ./stac/ /app/stac/

ENTRYPOINT ["bacon", "--headless", "run"]
